export const restaurantAdminEn = {
  confirmArea: "Confirm area",
  areaReason:
    "Independent evidence confirming this restaurant belongs in the selected area",
  discard: "Discard draft",
  title: "Restaurant picks",
  intro:
    "Review the restaurant pool, compare the top ten candidates, and approve the recommendation before publication.",
  noAreas: "No restaurant areas configured yet.",
  area: "Area",
  date: "Recommendation date",
  disabled: "disabled",
  prepare: "Queue recommendation",
  refresh: "Refresh",
  saved: "Saved. Queued work appears below when the worker processes it.",
  jobs: "Worker jobs",
  runs: "Recommendations",
  report: "Top-10 report",
  reportHelp:
    "The winner and strongest alternatives from this run’s evaluated pool. Fewer than ten appear when the pool is smaller.",
  candidate: "Restaurant",
  decision: "Decision",
  score: "Adjusted quality score",
  reason: "Reason",
  copy: "Recommendation text",
  approveCopy: "Approve copy",
  reject: "Reject copy",
  publish: "Queue publication",
  replace: "Replace the currently published pick for this date?",
  withdraw: "Withdraw",
  candidates: "Selection pool",
  unclassified: "Food type needs review",
  evidence: "Approved facts",
  foodType: "Set primary food type",
  fact: "Independent, permission-compatible fact (do not paste Google content)",
  source: "Source URL (optional)",
  addEvidence: "Add evidence",
  approve: "Approve candidate",
  exclude: "Exclude candidate",
  reasons: {
    lower_quality_score: "Lower adjusted quality score",
    rotation_tie_break: "Daily tie-break chose another candidate",
    editorial_selection: "Editorial selection",
    picked: "Picked",
    eligible_not_picked: "Eligible, another candidate ranked higher",
    excluded: "Excluded",
    quality_unknown: "Google quality data is missing or stale",
    rating_below_minimum: "Google rating is below the minimum",
    rating_count_below_minimum: "Not enough Google ratings",
    not_operational: "Not confirmed operational",
    hours_unknown: "Opening hours are unavailable",
    closed_on_date: "Closed on the selected date",
    service_finished: "Service has finished today",
    food_type_unknown: "Food type needs review",
    food_type_recent: "This food type conflicts with the seven-day rotation",
    restaurant_recent: "This restaurant was featured within 30 days",
    insufficient_evidence:
      "Not enough approved facts for a grounded recommendation",
    copy_failed: "Recommendation text could not be verified",
    area_unreviewed: "Location or publication approval is missing",
    highest_quality: "Highest qualifying quality score",
    lower_quality: "Lower adjusted quality score",
    deterministic_tie_break: "Daily tie-break chose another candidate",
    selected: "Best eligible candidate with approved evidence",
    queued: "Queued",
    running: "Running",
    succeeded: "Completed",
    failed: "Failed",
    prepare: "Prepare recommendation",
    publish: "Publish recommendation",
    ready_for_review: "Ready for review",
    published: "Published",
    pending: "Pending review",
    approved: "Approved",
    rejected: "Rejected",
    discovered: "Discovered",
    reviewing: "Under review",
    empty: "No eligible pick",
  },
};
export const restaurantAdminZh: typeof restaurantAdminEn = {
  confirmArea: "確認所屬區域",
  areaReason: "請提供可確認此餐廳位於所選區域的獨立佐證",
  discard: "捨棄草稿",
  title: "餐廳每日精選",
  intro: "審核餐廳候選池、比較前十名候選，並在發布前核准推薦內容。",
  noAreas: "尚未設定餐廳推薦區域。",
  area: "區域",
  date: "推薦日期",
  disabled: "已停用",
  prepare: "排入推薦佇列",
  refresh: "重新整理",
  saved: "已儲存。背景工作處理後，結果會顯示在下方。",
  jobs: "背景工作",
  runs: "推薦紀錄",
  report: "前十名候選報告",
  reportHelp:
    "顯示本次評估的入選餐廳與最具競爭力的其他候選；候選不足十家時，依實際數量顯示。",
  candidate: "餐廳",
  decision: "結果",
  score: "調整後品質分數",
  reason: "原因",
  copy: "推薦文案",
  approveCopy: "核准文案",
  reject: "退回文案",
  publish: "排入發布佇列",
  replace: "要取代此日期目前已發布的精選嗎？",
  withdraw: "撤回",
  candidates: "候選池",
  unclassified: "餐點類型待審核",
  evidence: "已核准事實",
  foodType: "設定主要餐點類型",
  fact: "獨立且已取得使用許可的事實（請勿貼上 Google 內容）",
  source: "來源網址（選填）",
  addEvidence: "新增佐證",
  approve: "核准候選",
  exclude: "排除候選",
  reasons: {
    lower_quality_score: "調整後品質分數較低",
    rotation_tie_break: "同分時依每日排序選擇其他候選",
    editorial_selection: "編輯精選",
    picked: "入選",
    eligible_not_picked: "符合資格，其他候選排名較高",
    excluded: "排除",
    quality_unknown: "Google 品質資料缺漏或過期",
    rating_below_minimum: "Google 評分低於門檻",
    rating_count_below_minimum: "Google 評分數量不足",
    not_operational: "尚未確認正常營業",
    hours_unknown: "無可用營業時間",
    closed_on_date: "指定日期未營業",
    service_finished: "今日營業已結束",
    food_type_unknown: "餐點類型待審核",
    food_type_recent: "餐點類型與七天輪替規則衝突",
    restaurant_recent: "三十天內已推薦此餐廳",
    insufficient_evidence: "已核准事實不足以支持推薦",
    copy_failed: "無法驗證推薦文案",
    area_unreviewed: "缺少地點或發布核准",
    highest_quality: "符合資格者中品質分數最高",
    lower_quality: "調整後品質分數較低",
    deterministic_tie_break: "同分時依每日排序選擇其他候選",
    selected: "具備核准佐證的最佳合格候選",
    queued: "已排入佇列",
    running: "處理中",
    succeeded: "已完成",
    failed: "失敗",
    prepare: "準備推薦",
    publish: "發布推薦",
    ready_for_review: "待審核",
    published: "已發布",
    pending: "待審核",
    approved: "已核准",
    rejected: "已退回",
    discovered: "已發現",
    reviewing: "審核中",
    empty: "無合格候選",
  },
};
